resolver: lts-14.1
packages:
- .
extra-deps:
  - ../jsem
#  - git: https://github.com/DaisukeBekki/JSeM.git
#    commit: f7f1bb847c4eb5e37ec54906e61a96a0b427692c
  - git: https://github.com/DaisukeBekki/lightblue.git
    commit: 420532a54bae200890116a336911eb0c114c8930
flags: {}
extra-package-dbs: []
